# -*- coding: utf-8 -*-
"""Day 2 mini project (list) Grade management

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mzi5c75uO_irE4vBa2OG0f6sRmXpkTZ4
"""

student_name = ["Potae", "Preme"]
student_scores = [94, 83]
while True:
    print("===== Student Grade Manager =====")
    print("1. Search student")
    print("2. Add student")
    print("3. Average Score")
    print("4. Exit")
    choice = input("Choose menu:")

    if choice == "1":
        search_name = input("Enter student name:")
        position = 0
        found = False

        for name in student_name:
            if search_name == name:
                score = student_scores[position]
                if score >= 80:
                    grade = "A"
                elif score >= 70:
                    grade = "B"
                elif score >= 60:
                    grade = "C"
                elif score >= 50:
                    grade = "D"
                else:
                    grade = "F"
                print("Student:", name)
                print("Score:", score)
                print("Grade:", grade)

                found = True
                break


            position += 1
        if not found:
            print("Student not found")

    elif choice == "2":
        new_student = input("Enter new student name:")
        new_score = int(input("Enter score:"))
        if new_score >= 0 and new_score <= 100:
            student_name.append(new_student)
            student_scores.append(new_score)
            print("Student added successfully")
            print("Student:", new_student)
            print("Score:", new_score)
        else:
            print("Score must be between 0 and 100.")

    elif choice == "3":
        total_score = 0
        student_count = 0
        if student_scores:
            for score in student_scores:
                total_score = total_score + score
                student_count = student_count + 1
            average_score = total_score / student_count
            print("Average score:", average_score)
        else:
            print("No students to calculate average score.")

    elif choice == "4":
        print("Goodbye!")
        break
    else:
        print("Invalid menu")