# -*- coding: utf-8 -*-
"""Mini project calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GyDufabkjjD5Xa0pjG0tG9CICCg1SQfc
"""

# level 1
# Mini project after Unit 2 variables and simple data types.
food_price = 120
drink_price = 45
other_price = 80
discount_rate = 0.10
subtotal = food_price + drink_price + other_price
print(subtotal)
discount = subtotal * discount_rate
print(discount)
total_discount = subtotal - discount
print(total_discount)
vat = total_discount * 0.07
total = total_discount + vat
choice = input()
print(f"Subtotal:{subtotal:.2f} baht")
print(f"Discount:{discount} baht")
print(f"Total:{total_discount} baht")
print(f"Vat:{vat:.2f} baht") #:0.2f floting 2 decimals
print(f"Total:{total:.2f} baht")

from IPython.core.interactiveshell import dis
# level 2 input()
food_price = float(input("Enter your food price"))
drink_price = float(input("Enter your drink price"))
other_price = float(input("Enter your other price"))
discount_rate = float(input("Enter your discount rate"))
subtotal = food_price + drink_price + other_price
print(subtotal)
discount = subtotal * (discount_rate/100)
print(discount)
Price_after_discount = subtotal - discount
print(Price_after_discount)
vat_input = float(input("Enter your vat"))
vat = Price_after_discount * (vat_input/100)
total = Price_after_discount + vat
print(f"Subtotal:{subtotal:.2f} baht")
print(f"Discount:{discount} baht")
print(f"Price after dicount:{Price_after_discount} baht")
print(f"Vat:{vat:.2f} baht") #:0.2f floting 2 decimals
print(f"Total:{total:.2f} baht")

#level 3
def calculate_total(food_price, drink_price, other_price, discount_rate, vat_rate):
    subtotal = food_price + drink_price + other_price
    discount = subtotal * (discount_rate/100)
    price_after_discount = subtotal - discount
    vat = price_after_discount * (vat_rate/100)
    total = price_after_discount + vat
    return total

result = calculate_total(120, 45, 80, 10, 7)
print(f"Total:{result:.2f} baht")

#level 4
# return more than 1 value
def calculate_total(food_price, drink_price, other_price, discount_rate, vat_rate):
    if food_price < 0 or drink_price < 0 or other_price < 0 or discount_rate < 0 or vat_rate < 0:
        print("Price can not be negative")
        return
    if discount_rate>100 or vat_rate>100:
        print("Discount and vat can not be more than 100%")
        return
    subtotal = food_price + drink_price + other_price
    discount = subtotal * (discount_rate/100)
    price_after_discount = subtotal - discount
    vat = price_after_discount * (vat_rate/100)
    total = price_after_discount + vat
    return subtotal, discount, price_after_discount, vat, total
while True:
    food_price = float(input("Enter your food price"))
    drink_price = float(input("Enter your drink price"))
    other_price = float(input("Enter your other price"))
    discount_rate = float(input("Enter your discount rate"))
    vat_rate = float(input("Enter your vat"))
    if (food_price >= 0
        and drink_price >= 0
        and other_price >= 0
        and 0<=discount_rate<=100
        and 0<=vat_rate<=100):
        break
    else:
        print("Price can not be negative")

subtotal, discount, price_after_discount, vat, total = calculate_total(food_price,
    drink_price,
    other_price,
    discount_rate,
    vat_rate)
print(f"Subtotal:{subtotal:.2f} baht")
print(f"Discount:{discount:.2f} baht")
print(f"Price after discount:{price_after_discount:.2f} baht")
print(f"Vat:{vat:.2f} baht")
print(f"Total:{total:.2f} baht")

# level 5 using while loop

from re import I
def calculate_cost(food_price, drink_price ,other_price,discount_rate,vat_rate):
    if (food_price < 0 or drink_price < 0 or other_price < 0 or discount_rate < 0 or vat_rate < 0):
        print("Price can not be negative")
        return
    if (discount_rate>100 or vat_rate>100):
        print("Discount and vat can not be more than 100%")
        return
    subtotal = food_price + drink_price + other_price
    discount = subtotal * (discount_rate/100)
    price_after_discount = subtotal - discount
    vat = price_after_discount * (vat_rate/100)
    total = price_after_discount + vat
    return subtotal, discount, price_after_discount, vat, total
    # finishing create function for calculate cost
# using while loop for user input
while True :
    food_price = float(input("Enter your food price"))
    drink_price = float(input("Enter your drink price"))
    other_price = float(input("Enter your other price"))
    discount_rate = float(input("Enter your discount rate"))
    vat_rate = float(input("Enter your vat"))
    if (
        food_price >= 0
        and drink_price >= 0
        and other_price >= 0
        and 0<=discount_rate<=100
        and 0<=vat_rate<=100
    ):
        break
    else:
        print("Prices must be non-negative, and rates must be between 0 and 100.")
      # finishing input for user
      # Implementation
subtotal, discount, price_after_discount, vat, total = calculate_cost(food_price,
    drink_price,
    other_price,
    discount_rate,
    vat_rate)
print(f"Subtotal:{subtotal:.2f} baht")
print(f"Discount:{discount:.2f} baht")
print(f"Price after discount:{price_after_discount:.2f} baht")
print(f"Vat:{vat:.2f} baht")
print(f"Total:{total:.2f} baht")