# -*- coding: utf-8 -*-
"""Day07 try-except.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iPMuAQumzPWmdfD6lxOZ6313oAMaCbgk
"""

# Commented out IPython magic to ensure Python compatibility.
# #writing module of input_utils.py
# %%writefile input_utils.py
# def get_float(prompt):
#     while True:
#         try:
#             value = float(input(prompt))
#             return value
#         except ValueError:
#             print("Please enter valid number: ")
# def get_int(prompt):
#     while True:
#         try:
#             value = int(input(prompt))
#             return value
#         except ValueError:
#             print("Please enter valid number: ")
# 
# def get_percentage(prompt):
#     while True:
#         try:
#             value = float(input("Please enter valid number: "))
# 
#             if 0 <= value <= 100:
#                 return value
#             else:
#                 print("Value must be between 0 and 100")
# 
#         except ValueError:
#             print("Pleas enter a valid number.")
# 
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.py
# from input_utils import get_float , get_int , get_percentage
# 
# gpu_usage = get_percentage("Enter GPU usages: ")
# requests = get_int("Enter number of requests: ")
# 
# print(f"GPU usage: {gpu_usage}%")
# print(f"Requests: {requests}")

!python main.py