# -*- coding: utf-8 -*-
"""Day05 Mini project : Server Resource Manager.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D-5nkyvivh9-P6wExU7Pw-1PuGPTZS1y
"""

# Day 05 Mini Project: Server Resource Manager

class Server:
    def __init__(self, name, cpu_usage, memory_usage, status):
        self.name = name
        self.cpu_usage = cpu_usage
        self.memory_usage = memory_usage
        self.status = status

    def show_status(self):
        print(f"Server: {self.name}")
        print(f"CPU Usage: {self.cpu_usage}%")
        print(f"Memory Usage: {self.memory_usage}%")
        print(f"Status: {self.status}")

    def update_usage(self, cpu_usage, memory_usage):
        if self.status == "Stopped":
            print("Cannot update usage while server is offline.")
            return
        if 0 <= cpu_usage <= 100 and 0 <= memory_usage <= 100:
            self.cpu_usage = cpu_usage
            self.memory_usage = memory_usage
            print("Resource usage updated successfully.")
        else:
            print("CPU and memory usage must be between 0 and 100.")

    def check_health(self):
        if self.status == "Stopped":
            print("Server is offline.")

        elif self.cpu_usage >= 90 or self.memory_usage >= 90:
            print("Critical!")

        elif self.cpu_usage >= 75 or self.memory_usage >= 75:
            print("Warning!")

        else:
            print("Healthy.")

    def start_server(self):
        if self.status == "Running":
            print(f"Server {self.name} is already running.")
        else:
            self.status = "Running"
            print(f"Server {self.name} started successfully.")

    def stop_server(self):
        if self.status == "Stopped":
            print(f"Server {self.name} is already stopped.")
        else:
            self.status = "Stopped"
            print(f"Server {self.name} stopped successfully.")

server_name = input("Enter server name: ")
while True:
    cpu_usage = float(input("Enter initial CPU usage: "))
    memory_usage = float(input("Enter initial memory usage: "))
    if 0<= cpu_usage <= 100 and 0 <= memory_usage <= 100:
        break

    print("CPU and memory usage must be between 0 and 100")

while True:
    status = input("Enter server status (Running/Stopped): ").strip().capitalize()
    if status == "Running" or status == "Stopped":
      break
    print("Status must be Running or Stopped.")

server01 = Server(server_name , cpu_usage , memory_usage , status)

while True:
    print("\n===== Server Resource Manager =====")
    print("1. Show Status")
    print("2. Update Usage")
    print("3. Check Health")
    print("4. Start Server")
    print("5. Stop Server")
    print("6. Exit")

    choice = input("Choose menu: ")

    if choice == "1":
        server01.show_status()

    elif choice == "2":
        cpu_usage = float(input("Enter CPU usage: "))
        memory_usage = float(input("Enter memory usage"))
        server01.update_usage(cpu_usage , memory_usage)

    elif choice == "3":
        server01.check_health()

    elif choice == "4":
        server01.start_server()

    elif choice == "5":
        server01.stop_server()

    elif choice == "6":
        print("Good bye!!")
        break
    else:
        print("Invalid menu")