# -*- coding: utf-8 -*-
"""Day06--mini project AI inference service Manager

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19c1SS2Y207o4IPngTYuYojJp_q8LkwnQ

**Day 6--mini project AI inference service Manager**
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile monitor.py
# def check_gpu(gpu_usage):
#     if gpu_usage >= 90:
#         print("GPU Critical")
#     elif gpu_usage >= 75:
#         print("GPU Warning")
#     else:
#         print("GPU healthy")
# 
# def check_requests(requests):
#     if requests >= 1000:
#         print("High traffic")
#     elif requests >= 500:
#         print("Medium traffic")
#     else:
#         print("Low traffic")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile main.py
# from monitor import check_gpu , check_requests
# gpu_usage = float(input("Enter GPU_usage: "))
# requests = int(input("Enter number of requests: "))
# 
# check_gpu(gpu_usage)
# check_requests(requests)

!python main.py