# -*- coding: utf-8 -*-
"""Day4 miniproject ATM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iS6k6ZNgDuUEI1LISYAE7ggCr791L3tP
"""

# Day 4 Mini Project: ATM

balance = 1000


def check_balance(current_balance):
    print(f"Your current balance is: {current_balance}")


def deposit(current_balance, amount):
    if amount > 0:
        current_balance += amount
        print("Deposit successful.")
        print(f"New balance is: {current_balance}")
        return current_balance
    else:
        print("Deposit amount must be greater than 0.")
        return current_balance


def withdraw(current_balance, amount):
    if amount <= 0:
        print("Withdrawal amount must be greater than 0.")
        return current_balance

    elif amount > current_balance:
        print("Insufficient balance.")
        return current_balance

    else:
        current_balance -= amount
        print("Withdrawal successful.")
        print(f"New balance is: {current_balance}")
        return current_balance


while True:
    print("\n===== ATM Management =====")
    print("1. Check Balance")
    print("2. Deposit")
    print("3. Withdraw")
    print("4. Exit")

    choice = input("Choose menu: ")

    if choice == "1":
        check_balance(balance)

    elif choice == "2":
        amount_to_deposit = float(input("Enter deposit amount: "))
        balance = deposit(balance, amount_to_deposit)

    elif choice == "3":
        amount_to_withdraw = float(input("Enter withdrawal amount: "))
        balance = withdraw(balance, amount_to_withdraw)

    elif choice == "4":
        print("Goodbye!")
        break

    else:
        print("Invalid menu.")