# -*- coding: utf-8 -*-
"""Day 3 mini project Inventory management (dictionary)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13KxIZwLsEkY-UrLiEXZCYZD1tpxzT-yB

**Day 3 Mini Project: Inventory Manager**
"""

products = {
    "Apple" : 10,
    "Banana" : 4,
    "Milk" : 8
}
while True :
    print("\n=====Inventory Management=====")
    print("1.Show Product")
    print("2.Search Product")
    print("3.Add Product")
    print("4.Update Product")
    print("5.Delete Product")
    print("6.Exit")

    choice = input("Enter your menu: ")

    if choice == "1":
        for product in products:
            stock = products[product]
            if stock < 5 :
                print(f"Product: {product} Stock: {stock} (Low Stock)")
            else:
                print(f"Product: {product} Stock: {stock}")


    elif choice == "2":
        search_product = input("Enter your product: ")

        if search_product in products:
            print(f"Product: {search_product}")
            print(f"Stock: {products[search_product]}")
        else:
            print("Product not found")

    elif choice == "3":
        new_item = input("Enter your item: ")
        if new_item in products:
            print("Product already exists")
        else:
            new_stock = int(input("Enter your stock: "))
            if new_stock >= 0:
                products[new_item] = new_stock
                print(f"Adding {new_item} sucessfully")
                print(f"Product: {new_item}")
                print(f"Stock: {new_stock}")
            else:
                print("Stock number cannot be negative.")

    elif choice == "4":
        updated_item = input("Enter your item: ")

        if updated_item in products:
            print(f"Product: {updated_item} Stock: {products[updated_item]}") # Fixed: Changed product[updated_item] to products[updated_item]

            new_stock_2 = int(input("Enter your stocks"))

            if new_stock_2 >= 0:
                products[updated_item] = new_stock_2
                print("Updated successfully")
            else:
                print("Stock number cannot be negative")
        else:
            print("Product not found")

    elif choice == "5":

        deleted_product = input("Enter your product name:")

        if deleted_product in products:
            del products[deleted_product]
            print("Product deleted successfully")

        else:
            print("Product not found")

    elif choice == "6":
        print("Good bye")

        break

    else:
        print("Invalid menu")