# -*- coding: utf-8 -*-
"""Day08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WqCglbTXg93BiMZzF2Dfs4iJch2Ct8up
"""

# Commented out IPython magic to ensure Python compatibility.
# 
# %%writefile application.py
# class jobapplication:
#     def __init__(self , company , role , status):
#         self.company = company
#         self.role = role
#         self.status = status
# 
#     def show_info(self):
#         print(f"Company: {self.company}")
#         print(f"Role : {self.role}")
#         print(f"Status: {self.status}")
# 
#     def update_status(self,new_status):
#         clean_status = new_status.strip()
# 
#         if clean_status == "":
#             print("New status cannot be empty")
# 
#         elif self.status == clean_status:
#             print("This status already exists.")
# 
#         else:
#             self.status = clean_status
#             print(f"Status updated to: {self.status}")
# 
# 
# 
# 
# 
#

# Commented out IPython magic to ensure Python compatibility.
# # Receive input
# %%writefile input.py
# def get_non_empty(prompt):
#     while True:
#         text =input(prompt)
#         clean_text = text.strip().capitalize()
# 
#         if clean_text == "":
#             print("Invalid text")
#         elif clean_text.isdigit():
#             print("Invalid text")
#         else:
#             return clean_text
# 
# def get_menu_choice(prompt , valid_choice):
#     while True:
#         choice = input(prompt)
# 
#         if choice in valid_choice:
#             return choice
# 
#         print("Invalid text")
#

# Commented out IPython magic to ensure Python compatibility.
# 
# %%writefile main.py
# from application import jobapplication
# from input import get_non_empty, get_menu_choice
# 
# print("===== AI Job Application Tracker =====")
# 
# company = get_non_empty("Pls enter a company: ")
# role = get_non_empty("Pls enter a role: ")
# status = get_non_empty("Pls enter status: ")
# 
# application = jobapplication(company, role , status)
# while True:
#     print("\n1. Show Application")
#     print("2. Update Status")
#     print("3. Exit")
# 
#     choice = get_menu_choice("Choose menu: " , ["1", "2", "3"])
# 
#     if choice == "1":
#         application.show_info()
# 
#     elif choice == "2":
#         new_status = get_non_empty("Pls enter new status")
#         application.update_status(new_status)
# 
#     elif choice == "3":
#         print("Good Bye!")
#         break
#

!python main.py